---
lucky:
  word: Rabbit's Foot
spring:
  jpa:
    hibernate:
      ddl-auto: create
eureka:
  client:
    serviceUrl:
      defaultZone: http://fleamarket-eureka-server.cfapps.io/eureka
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
