spring:
  jpa:
    hibernate:
      ddl-auto: create
lucky:
  word: Rabbit's Foot
eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.service-registry.credentials.uri:http://localhost:8282}/eureka
