---
lucky:
  word: Rabbit's Foot
spring:
  jpa:
    hibernate:
      ddl-auto: create
eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.service-registry.credentials.uri:http://localhost:8282}/eureka
